#!/usr/bin/env node
// Keeps the site's crawl surface current: the landing page's SEO block (the one
// hand-authored page), sitemap.xml and robots.txt. Generated pages get the same
// head from site-seo.mjs through their own builders.
//
// sitemap lastmod is the date of the last commit that touched each page, or
// today for a page with uncommitted changes, so it stays accurate.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { absoluteUrl, seoHead, softwareApplication } from './site-seo.mjs';
import { FAQ, RECIPES } from './site-content.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const docs = path.join(repoRoot, 'docs');
const packageJson = JSON.parse(fs.readFileSync(path.join(repoRoot, 'mosofin/package.json'), 'utf8'));

// ---- landing page SEO block
const landingPath = path.join(docs, 'index.html');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
// The visible FAQ and its FAQPage data come from one list, so they always match.
const FAQ_START = '      <!-- FAQ:START (generated by scripts/build-seo.mjs from scripts/site-content.mjs) -->';
const FAQ_END = '      <!-- FAQ:END -->';
let landing = fs.readFileSync(landingPath, 'utf8');
{
  const a = landing.indexOf(FAQ_START);
  const b = landing.indexOf(FAQ_END);
  if (a < 0 || b < a) throw new Error('docs/index.html is missing the FAQ markers');
  const items = FAQ.map((item, index) => {
    const border = index === FAQ.length - 1 ? 'border-top:1px solid #e6e8ec;border-bottom:1px solid #e6e8ec' : 'border-top:1px solid #e6e8ec';
    return `      <details style="${border};padding:18px 0"${index === 0 ? ' open' : ''}>
        <summary style="cursor:pointer;font-size:16px;font-weight:700;color:#0a0b0d;list-style:none"><h3 style="display:inline;font:inherit;margin:0">${escapeHtml(item.q)}</h3></summary>
        <p style="margin:10px 0 0;font-size:14.5px;line-height:1.7;color:#5c6370;max-width:60ch">${escapeHtml(item.a)}</p>
      </details>`;
  }).join('\n');
  landing = `${landing.slice(0, a + FAQ_START.length)}\n${items}\n${landing.slice(b)}`;
}
const title = landing.match(/<title>([^<]+)<\/title>/)[1];
const description = landing.match(/<meta name="description" content="([^"]+)">/)[1];
const block = seoHead({
  path: '/',
  title,
  description,
  jsonLd: [
    softwareApplication(packageJson.version),
    {
      '@type': 'FAQPage',
      mainEntity: FAQ.map((item) => ({ '@type': 'Question', name: item.q, acceptedAnswer: { '@type': 'Answer', text: item.a } })),
    },
  ],
});
const START = '  <!-- SEO:START (generated by scripts/build-seo.mjs) -->';
const END = '  <!-- SEO:END -->';
const a = landing.indexOf(START);
const b = landing.indexOf(END);
if (a < 0 || b < a) throw new Error('docs/index.html is missing the SEO markers');
fs.writeFileSync(landingPath, `${landing.slice(0, a + START.length)}\n${block}\n${landing.slice(b)}`);

// ---- sitemap
const today = new Date().toISOString().slice(0, 10);
function lastmod(file) {
  const rel = path.relative(repoRoot, file);
  const dirty = execFileSync('git', ['status', '--porcelain', '--', rel], { cwd: repoRoot, encoding: 'utf8' }).trim();
  if (dirty) return today;
  const date = execFileSync('git', ['log', '-1', '--format=%cs', '--', rel], { cwd: repoRoot, encoding: 'utf8' }).trim();
  return date || today;
}
const manifest = JSON.parse(fs.readFileSync(path.join(docs, 'gallery/manifest.json'), 'utf8'));
const galleryArtifacts = manifest.entries.map((entry) => entry.artifact);
const galleryStems = new Set(galleryArtifacts.map((artifact) => path.basename(artifact).replace(/\.[a-z]+\.html$/, '')));
// A sample that renders the same spec as a gallery artifact is a duplicate page;
// list the gallery copy only, which is the one the site links to.
const samples = fs.readdirSync(path.join(docs, 'samples'))
  .filter((name) => name.endsWith('.html') && !name.includes('visual-check'))
  .filter((name) => !galleryStems.has(name.replace(/\.html$/, '')))
  .sort()
  .map((name) => `samples/${name}`);
const pages = [
  ['', 'index.html', '1.0'],
  ['start.html', 'start.html', '0.9'],
  ['gallery.html', 'gallery.html', '0.9'],
  ['guide.html', 'guide.html', '0.8'],
  ['logos.html', 'logos.html', '0.7'],
  ['recipes/', 'recipes/index.html', '0.8'],
  ...RECIPES.map((recipe) => [`recipes/${recipe.id}.html`, `recipes/${recipe.id}.html`, '0.7']),
  ...galleryArtifacts.map((rel) => [rel, rel, '0.6']),
  ...samples.map((rel) => [rel, rel, '0.5']),
];
const urls = pages.map(([rel, file, priority]) => `  <url><loc>${absoluteUrl(`/${rel}`)}</loc><lastmod>${lastmod(path.join(docs, file))}</lastmod><priority>${priority}</priority></url>`);
fs.writeFileSync(path.join(docs, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`);

// ---- robots: the design handoff is an internal snapshot that duplicates the site.
// AI assistants and answer engines are named explicitly: a crawler that matches
// its own group ignores the * group, so each group repeats the one Disallow.
const AI_CRAWLERS = [
  'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-User', 'Claude-SearchBot',
  'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'Applebot-Extended', 'Amazonbot', 'CCBot',
];
fs.writeFileSync(path.join(docs, 'robots.txt'), [
  'User-agent: *',
  'Allow: /',
  'Disallow: /design-handoff/',
  '',
  '# AI assistants and answer engines are welcome to read, cite and use this site.',
  '# Start with /llms.txt; everything an agent needs is in /llms-full.txt.',
  ...AI_CRAWLERS.map((agent) => `User-agent: ${agent}`),
  'Allow: /',
  'Disallow: /design-handoff/',
  '',
  `Sitemap: ${absoluteUrl('/sitemap.xml')}`,
  '',
].join('\n'));
console.log(`seo: landing head, ${urls.length} sitemap URLs, robots.txt`);
